config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true
  validates :start_day, presence: true
  validates :end_day, presence: true
  validate :start_day_check
  validate :end_day_check

  def start_day_check
    if start_day.blank?
      return
    elsif start_day < Date.today - 1
      errors.add(:start_day,"は今日以降の日付を選択して下さい")
    end
  end

  def end_day_check
    if end_day.blank?
      return
    elsif end_day < start_day - 1
      errors.add(:end_day,"は開始日以降の日付を選択して下さい") 
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all.order(:start_day)
  end
  
  def new
    @schedule = Schedule.new
  end
  
  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start_day, :end_day, :all_day, :memo))
    if @schedule.save
      flash[:notice] = "スケジュールを新規登録しました"
      redirect_to schedules_path
    else
      flash[:notice] = "スケジュールの登録が出来ませんでした"
      render "new"
    end
  end
  
  def show
    @schedule = Schedule.find(params[:id])
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
  end
  
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start_day, :end_day, :all_day, :memo))
      flash[:notice] = "IDが「#{@schedule.id}」のスケジュールを更新しました"
      redirect_to schedules_path
    else
      flash[:notice] = "スケジュールの更新が出来ませんでした"
      render "edit"
    end
  end
  
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to schedules_path
  end
  
  def current
    @current = Date.current.strftime("%Y年 %m月 %d日")
  end

  before_action :current, oniy: [:index, :new, :show, :edit]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduleapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>

    <div class="main_container">
      <%= yield %>
    </div>
  
    <footer>
      <h1>現在の日時:<%= @current %>
      <% case controller.action_name %>
        <% when "index" %>
          <span>スケジュール合計:<%= @schedules.count %></span>
        <% else %>

      <% end %>
      </h1>
    </footer>

  </body>
</html>

app/views/schedules/edit.html.erb
<h2>スケジュール編集</h2>

<% if flash[:notice] %>
 <p class="notice"><%= flash[:notice] %></p>
<% end %>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule, local: true do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :start_day ,"開始日" %></th>
      <td><%= f.date_field :start_day %></td>
    </tr>
    <tr>
      <th><%= f.label :end_day ,"終了日" %></th>
      <td><%= f.date_field :end_day %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day ,"終日" %></th>
      <td>
        <%= f.check_box :all_day, {}, checked_value='true', unchecked_value='false' %>
        <br>終日の場合はチェックを入れて下さい
      </td>
    </tr>
    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "スケジュールの編集を完了する", class: "button" %></li>
      <li><%= link_to "スケジュール一覧に戻る", schedules_path %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/index.html.erb
<!-- <h1>Schedules#index</h1>
<p>Find me in app/views/schedules/index.html.erb</p> -->
<h2>スケジュール一覧</h2>

<% if flash[:notice] %>
 <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>スケジュール更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.title %></td>
        <td><%= schedule.start_day.to_s(:date_jp) %></td>
        <td><%= schedule.end_day.to_s(:date_jp) %></td>
        <td>
          <% if schedule.all_day == true %>
          ○
          <% else schedule.all_day == false %>

          <% end %>
        </td>
        <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "確認", schedule_path(schedule) %></td>
        <td><%= link_to "編集", edit_schedule_path(schedule) %></td>
        <td><%= link_to "削除", schedule_path(schedule), method: :delete, data:{confirm: "本当に削除して宜しいですか？"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "スケジュール新規登録", new_schedule_path %></p>

app/views/schedules/new.html.erb
<h2>スケジュール新規登録</h2>

<% if flash[:notice] %>
 <p class="notice"><%= flash[:notice] %></p>
<% end %>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule, local: true do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :start_day ,"開始日" %></th>
      <td><%= f.date_field :start_day %></td>
    </tr>
    <tr>
      <th><%= f.label :end_day ,"終了日" %></th>
      <td><%= f.date_field :end_day %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day ,"終日" %></th>
      <td>
        <%= f.check_box :all_day, {}, checked_value='true', unchecked_value='false' %>
        <br>終日の場合はチェックを入れて下さい
      </td>
    </tr>
    <tr>
      <th><%= f.label :memo ,"スケジュールメモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "スケジュールを新規登録する", class: "button" %></li>
      <li><%= link_to "スケジュール一覧に戻る", schedules_path %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/show.html.erb
<h2>スケジュール詳細</h2>

<table>
  <tr>
    <th>タイトル</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @schedule.start_day.to_s(:date_jp) %></td>
  </tr>
  <tr>
    <th>投稿日時</th>
    <td><%= @schedule.created_at.to_s(:datetime_jp) %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td>
      <% if @schedule.all_day == true %>
      ○
      <% else @schedule.all_day == false %>

      <% end %>
      </td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @schedule.memo %></td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to "スケジュール一覧に戻る", schedules_path %></li>
    <li><%= link_to "スケジュールを編集する", edit_schedule_path %></li>
    <li><%= link_to "スケジュールを削除する", schedule_path, method: :delete, data:{confirm: "本当に削除して宜しいですか？"} %></li>
  </ul>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>